inputs:
  ligand_protein_paths:
    type:
      type: array
      items: File
  inference_steps:
    type: int
  samples_per_complex:
    type: int
  batch_size:
    type: int
  actual_steps:
    type: int
  no_final_step_noise:
    type: boolean
  top_n_confident:
    type: float
  top_percent_confidence:
    type: float
  centroid_cutoff:
    type: float
  use_clustering_filter:
    type: boolean
  cache:
    type:
      type: array
      items: File


steps:
    - extract_zipped_files:
        in:
          zipped_array: ~ligand_protein_paths
          first_file: "&protein_file"
          second_file: "&ligand_file"

    - sanitize_mol:
        in:
          ligand_path: "*ligand_file"
          output_file: "&output_file"

    - gen_diffdock_inputs:
        in:
          protein_path: "*protein_file"
          ligand_path: "*output_file"
          output: "&diffdock_input_file"
          protein_path_out: "&protein_path"
          ligand_path_out: "&ligand_path"

    - diffdock_gpu:
        in:
          script_path: "diffdock_cmds.sh"
          cached_files: ~cache
          protein_ligand_inputs: "*diffdock_input_file"
          protein_path: "*protein_path"
          ligand_path: "*output_file"
          inference_steps: ~inference_steps
          samples_per_complex: ~samples_per_complex
          batch_size: ~batch_size
          actual_steps: ~actual_steps
          no_final_step_noise: ~no_final_step_noise
          output_files: "&diffdock_poses"
          execution_time: "&execution_time"

    - diffdock_rank_poses:
        in:
          top_n_confident: ~top_n_confident
          top_percent_confidence: ~top_percent_confidence
          output_files_path: "*diffdock_poses"
          output_poses: "&output_poses"
          output_diffusion_trajectory: "&diffusion_trajectory"

    - modify_filenames:
        in:
          file_names: "*diffusion_trajectory"
          inference_steps: ~inference_steps
          samples_per_complex: ~samples_per_complex
          output_files: "&mod_diffusion_trajectory"

    - modify_filenames:
        in:
          file_names: "*output_poses"
          inference_steps: ~inference_steps
          samples_per_complex: ~samples_per_complex
          output_files: "&mod_output_files"

    - rmsd_pose_filter:
        in:
          crystal_pose_path: "*ligand_path"
          predicted_poses: "*mod_output_files"
          diffusion_trajectory: "*mod_diffusion_trajectory"
          rmsd_json: "&rmsd"
          centroid_cutoff: ~centroid_cutoff
          filtered_poses: "&filtered_poses"
          use_clustering_filter: ~use_clustering_filter

    - pymol_superpose:
        in:
          crystal_pose_path: "*ligand_path"
          pdb_path: "*protein_path"
          predicted_poses: "*filtered_poses"
          output_pymol_session: "&output_pymol_session"

    - output_diffdock_parameters:
        in:
          top_percent_confidence: ~top_percent_confidence
          execution_time: "*execution_time"
          rmsd: "*rmsd"
          output_json: "&output_json"
          protein_path: "*protein_file"
          ligand_path: "*output_file"
          inference_steps: ~inference_steps
          samples_per_complex: ~samples_per_complex
          batch_size: ~batch_size
          actual_steps: ~actual_steps
          no_final_step_noise: ~no_final_step_noise
          top_n_confident: ~top_n_confident
          pymol_session: "*output_pymol_session"