
# docker build -f Dockerfile_pymol_superpose .

FROM continuumio/miniconda3:4.12.0


RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    p7zip-full ffmpeg libsm6 libxext6 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN conda config --add channels conda-forge

RUN conda config --set channel_priority strict

RUN conda install pymol-open-source==2.5.0 --yes

RUN conda init bash

COPY pymol_superpose.py /. 
